import type { CatalogItem } from "../../types";

/** Frozen KT-PB-2026.1 canonical catalog items (chargeable + typed objects). */
export const CATALOG_ITEMS: CatalogItem[] = [
  {
    code: "WEB-ONE",
    name: "One Page",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 500000,
    billing: "ONE_TIME",
    timelineMinDays: 7,
    timelineMaxDays: 10,
    timelineImpactDays: null,
    clientDescription: "1 custom scrolling page · up to 8 sections",
    active: true,
    sortOrder: 1,
  },
  {
    code: "WEB-ESS",
    name: "Essential",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 900000,
    billing: "ONE_TIME",
    timelineMinDays: 14,
    timelineMaxDays: 21,
    timelineImpactDays: null,
    clientDescription: "Up to 5 pages · custom design · CMS for agreed content",
    active: true,
    sortOrder: 2,
  },
  {
    code: "WEB-BUS",
    name: "Business",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 1500000,
    billing: "ONE_TIME",
    timelineMinDays: 14,
    timelineMaxDays: 21,
    timelineImpactDays: null,
    clientDescription: "Up to 10 pages · enhanced custom design · CMS · blog/news · portfolio",
    active: true,
    sortOrder: 3,
  },
  {
    code: "WEB-BUSP",
    name: "Business+",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 2250000,
    billing: "ONE_TIME",
    timelineMinDays: 16,
    timelineMaxDays: 21,
    timelineImpactDays: null,
    clientDescription: "Up to 15 pages · custom UX/UI · CMS · projects/case studies · team · resources",
    active: true,
    sortOrder: 4,
  },
  {
    code: "WEB-PRO",
    name: "Professional",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 3250000,
    billing: "ONE_TIME",
    timelineMinDays: 18,
    timelineMaxDays: 21,
    timelineImpactDays: null,
    clientDescription: "Up to 20 pages/templates · advanced architecture",
    active: true,
    sortOrder: 5,
  },
  {
    code: "WEB-SIG",
    name: "Signature",
    kind: "PACKAGE",
    category: "Websites",
    priceTsh: 4500000,
    billing: "ONE_TIME",
    timelineMinDays: 18,
    timelineMaxDays: 21,
    timelineImpactDays: null,
    clientDescription: "Bespoke UX/UI · premium interactions",
    active: true,
    sortOrder: 6,
  },
  {
    code: "WEB-CUS",
    name: "Custom Platform",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Websites",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Portals · databases · dashboards · complex integrations",
    active: true,
    sortOrder: 7,
  },
  {
    code: "ADD-PAGE",
    name: "Additional standard page",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 100000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Additional standard page",
    active: true,
    sortOrder: 8,
  },
  {
    code: "ADD-LAND",
    name: "Custom landing page",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Custom landing page",
    active: true,
    sortOrder: 9,
  },
  {
    code: "ADD-BLOG",
    name: "Blog / News",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Blog / News",
    active: true,
    sortOrder: 10,
  },
  {
    code: "ADD-PORT",
    name: "Projects / Portfolio",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Projects / Portfolio",
    active: true,
    sortOrder: 11,
  },
  {
    code: "ADD-CASE",
    name: "Case Studies",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Case Studies",
    active: true,
    sortOrder: 12,
  },
  {
    code: "ADD-TEAM",
    name: "Team / Leadership",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 200000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Team / Leadership",
    active: true,
    sortOrder: 13,
  },
  {
    code: "ADD-CARE",
    name: "Careers / Vacancies",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Careers / Vacancies",
    active: true,
    sortOrder: 14,
  },
  {
    code: "ADD-RES",
    name: "Resource Centre",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Resource Centre",
    active: true,
    sortOrder: 15,
  },
  {
    code: "ADD-EVT",
    name: "Events",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Events",
    active: true,
    sortOrder: 16,
  },
  {
    code: "ADD-SRCH",
    name: "Advanced Site Search",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Advanced Site Search",
    active: true,
    sortOrder: 17,
  },
  {
    code: "ADD-MULTI",
    name: "Multi-location Directory",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Multi-location Directory",
    active: true,
    sortOrder: 18,
  },
  {
    code: "ADD-MAP",
    name: "Interactive Map",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Interactive Map",
    active: true,
    sortOrder: 19,
  },
  {
    code: "ADD-INQ",
    name: "Advanced Inquiry Form",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Advanced Inquiry Form",
    active: true,
    sortOrder: 20,
  },
  {
    code: "ADD-STEP",
    name: "Multi-step Form",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Multi-step Form",
    active: true,
    sortOrder: 21,
  },
  {
    code: "ADD-QUOTE",
    name: "Quote Request System",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Quote Request System",
    active: true,
    sortOrder: 22,
  },
  {
    code: "ADD-FILE",
    name: "File Uploads",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 100000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "File Uploads",
    active: true,
    sortOrder: 23,
  },
  {
    code: "ADD-FEED",
    name: "Social Feed",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Feed",
    active: true,
    sortOrder: 24,
  },
  {
    code: "ADD-BOT",
    name: "Website Chatbot",
    kind: "SERVICE",
    category: "Website Features",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Website Chatbot",
    active: true,
    sortOrder: 25,
  },
  {
    code: "BKG-EXT",
    name: "External Booking Integration",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "External Booking Integration",
    active: true,
    sortOrder: 26,
  },
  {
    code: "BKG-APT",
    name: "Appointment Booking",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Appointment Booking",
    active: true,
    sortOrder: 27,
  },
  {
    code: "BKG-STAFF",
    name: "Multi-staff Booking",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 1250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Multi-staff Booking",
    active: true,
    sortOrder: 28,
  },
  {
    code: "BKG-REST",
    name: "Restaurant Reservations",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 600000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Restaurant Reservations",
    active: true,
    sortOrder: 29,
  },
  {
    code: "BKG-TOUR",
    name: "Tour / Activity Booking",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 900000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Tour / Activity Booking",
    active: true,
    sortOrder: 30,
  },
  {
    code: "BKG-HOTINT",
    name: "Hotel Booking Integration",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Hotel Booking Integration",
    active: true,
    sortOrder: 31,
  },
  {
    code: "BKG-HOTCUS",
    name: "Custom Hotel Booking",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 2000000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Custom Hotel Booking",
    active: true,
    sortOrder: 32,
  },
  {
    code: "BKG-CAL",
    name: "Availability Calendar",
    kind: "SERVICE",
    category: "Booking",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Availability Calendar",
    active: true,
    sortOrder: 33,
  },
  {
    code: "PAY-STD",
    name: "Standard Payment Integration",
    kind: "SERVICE",
    category: "Payments",
    priceTsh: 500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Standard Payment Integration",
    active: true,
    sortOrder: 34,
  },
  {
    code: "PAY-DEP",
    name: "Deposit Payments",
    kind: "SERVICE",
    category: "Payments",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Deposit Payments",
    active: true,
    sortOrder: 35,
  },
  {
    code: "PAY-REC",
    name: "Recurring Payments",
    kind: "SERVICE",
    category: "Payments",
    priceTsh: 750000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Recurring Payments",
    active: true,
    sortOrder: 36,
  },
  {
    code: "PAY-DON",
    name: "Donation Payments",
    kind: "SERVICE",
    category: "Payments",
    priceTsh: 500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Donation Payments",
    active: true,
    sortOrder: 37,
  },
  {
    code: "PAY-API",
    name: "Custom / Direct Payment API",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Payments",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Custom / Direct Payment API",
    active: true,
    sortOrder: 38,
  },
  {
    code: "ECOM-START",
    name: "Starter Store",
    kind: "SUBSCRIPTION_TIER",
    category: "E-commerce",
    priceTsh: 1500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Starter Store",
    active: true,
    sortOrder: 39,
  },
  {
    code: "ECOM-BUS",
    name: "Business Store",
    kind: "SUBSCRIPTION_TIER",
    category: "E-commerce",
    priceTsh: 2500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Business Store",
    active: true,
    sortOrder: 40,
  },
  {
    code: "ECOM-ADV",
    name: "Advanced Store",
    kind: "SUBSCRIPTION_TIER",
    category: "E-commerce",
    priceTsh: 4000000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Advanced Store",
    active: true,
    sortOrder: 41,
  },
  {
    code: "ECOM-CUS",
    name: "Custom Commerce",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "E-commerce",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Custom Commerce",
    active: true,
    sortOrder: 42,
  },
  {
    code: "LANG-ENSW",
    name: "Bilingual website functionality",
    kind: "SERVICE",
    category: "Languages",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription:
      "Two-language website functionality (any language pair, as scoped)",
    active: true,
    sortOrder: 43,
  },
  {
    code: "LANG-ADD",
    name: "Each additional language",
    kind: "SERVICE",
    category: "Languages",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Each additional language",
    active: true,
    sortOrder: 44,
  },
  {
    code: "LANG-TRANS",
    name: "Professional translation",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Languages",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Professional translation",
    active: true,
    sortOrder: 45,
  },
  {
    code: "TOUR-CAT",
    name: "Tour/Safari Catalogue",
    kind: "SERVICE",
    category: "Industry · Tourism",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Tour/Safari Catalogue",
    active: true,
    sortOrder: 46,
  },
  {
    code: "TOUR-ITIN",
    name: "Itinerary Templates",
    kind: "SERVICE",
    category: "Industry · Tourism",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Itinerary Templates",
    active: true,
    sortOrder: 47,
  },
  {
    code: "TOUR-INQ",
    name: "Tour Inquiry",
    kind: "SERVICE",
    category: "Industry · Tourism",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Tour Inquiry",
    active: true,
    sortOrder: 48,
  },
  {
    code: "TOUR-BUILD",
    name: "Itinerary Builder",
    kind: "SERVICE",
    category: "Industry · Tourism",
    priceTsh: 900000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Itinerary Builder",
    active: true,
    sortOrder: 49,
  },
  {
    code: "RE-LIST",
    name: "Property Listings",
    kind: "SERVICE",
    category: "Industry · Real Estate",
    priceTsh: 650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Property Listings",
    active: true,
    sortOrder: 50,
  },
  {
    code: "RE-FILT",
    name: "Search & Filters",
    kind: "SERVICE",
    category: "Industry · Real Estate",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Search & Filters",
    active: true,
    sortOrder: 51,
  },
  {
    code: "RE-AGENT",
    name: "Agent Profiles",
    kind: "SERVICE",
    category: "Industry · Real Estate",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Agent Profiles",
    active: true,
    sortOrder: 52,
  },
  {
    code: "RE-INQ",
    name: "Property Inquiry",
    kind: "SERVICE",
    category: "Industry · Real Estate",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Property Inquiry",
    active: true,
    sortOrder: 53,
  },
  {
    code: "RE-MAP",
    name: "Property Map",
    kind: "SERVICE",
    category: "Industry · Real Estate",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Property Map",
    active: true,
    sortOrder: 54,
  },
  {
    code: "REST-MENU",
    name: "Digital Menu",
    kind: "SERVICE",
    category: "Industry · Restaurant",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Digital Menu",
    active: true,
    sortOrder: 55,
  },
  {
    code: "REST-AMENU",
    name: "Advanced Menu",
    kind: "SERVICE",
    category: "Industry · Restaurant",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Advanced Menu",
    active: true,
    sortOrder: 56,
  },
  {
    code: "REST-ORDER",
    name: "Online Ordering",
    kind: "SERVICE",
    category: "Industry · Restaurant",
    priceTsh: 900000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Online Ordering",
    active: true,
    sortOrder: 57,
  },
  {
    code: "REST-BRANCH",
    name: "Multi-branch",
    kind: "SERVICE",
    category: "Industry · Restaurant",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Multi-branch",
    active: true,
    sortOrder: 58,
  },
  {
    code: "REST-QR",
    name: "QR Menu",
    kind: "SERVICE",
    category: "Industry · Restaurant",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "QR Menu",
    active: true,
    sortOrder: 59,
  },
  {
    code: "EDU-ADM",
    name: "Admissions",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Admissions",
    active: true,
    sortOrder: 60,
  },
  {
    code: "EDU-FAC",
    name: "Faculty Directory",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Faculty Directory",
    active: true,
    sortOrder: 61,
  },
  {
    code: "EDU-COURSE",
    name: "Course Catalogue",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Course Catalogue",
    active: true,
    sortOrder: 62,
  },
  {
    code: "EDU-STUD",
    name: "Student Portal",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 2000000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Student Portal",
    active: true,
    sortOrder: 63,
  },
  {
    code: "EDU-PAR",
    name: "Parent Portal",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 2000000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Parent Portal",
    active: true,
    sortOrder: 64,
  },
  {
    code: "EDU-FEE",
    name: "Fee Payments",
    kind: "SERVICE",
    category: "Industry · Education",
    priceTsh: 750000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Fee Payments",
    active: true,
    sortOrder: 65,
  },
  {
    code: "NGO-PROG",
    name: "Programs / Projects",
    kind: "SERVICE",
    category: "Industry · NGO",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Programs / Projects",
    active: true,
    sortOrder: 66,
  },
  {
    code: "NGO-PUB",
    name: "Publications",
    kind: "SERVICE",
    category: "Industry · NGO",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Publications",
    active: true,
    sortOrder: 67,
  },
  {
    code: "NGO-VOL",
    name: "Volunteer Applications",
    kind: "SERVICE",
    category: "Industry · NGO",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Volunteer Applications",
    active: true,
    sortOrder: 68,
  },
  {
    code: "NGO-PORT",
    name: "Donor Portal",
    kind: "SERVICE",
    category: "Industry · NGO",
    priceTsh: 1750000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Donor Portal",
    active: true,
    sortOrder: 69,
  },
  {
    code: "HLTH-DIR",
    name: "Practitioner Directory",
    kind: "SERVICE",
    category: "Industry · Healthcare",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Practitioner Directory",
    active: true,
    sortOrder: 70,
  },
  {
    code: "HLTH-FORM",
    name: "Patient Forms",
    kind: "SERVICE",
    category: "Industry · Healthcare",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Patient Forms",
    active: true,
    sortOrder: 71,
  },
  {
    code: "HLTH-PORT",
    name: "Patient Portal",
    kind: "SERVICE",
    category: "Industry · Healthcare",
    priceTsh: 2500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Patient Portal",
    active: true,
    sortOrder: 72,
  },
  {
    code: "HLTH-TELE",
    name: "Teleconsult Integration",
    kind: "SERVICE",
    category: "Industry · Healthcare",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Teleconsult Integration",
    active: true,
    sortOrder: 73,
  },
  {
    code: "LOG-QUOTE",
    name: "Quote Workflow",
    kind: "SERVICE",
    category: "Industry · Logistics",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Quote Workflow",
    active: true,
    sortOrder: 74,
  },
  {
    code: "LOG-INQ",
    name: "Shipment Inquiry",
    kind: "SERVICE",
    category: "Industry · Logistics",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Shipment Inquiry",
    active: true,
    sortOrder: 75,
  },
  {
    code: "LOG-TRACK",
    name: "Tracking Interface",
    kind: "SERVICE",
    category: "Industry · Logistics",
    priceTsh: 650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Tracking Interface",
    active: true,
    sortOrder: 76,
  },
  {
    code: "LOG-API",
    name: "Live Tracking API",
    kind: "SERVICE",
    category: "Industry · Logistics",
    priceTsh: 1250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Live Tracking API",
    active: true,
    sortOrder: 77,
  },
  {
    code: "LOG-PORT",
    name: "Customer Portal",
    kind: "SERVICE",
    category: "Industry · Logistics",
    priceTsh: 2000000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Customer Portal",
    active: true,
    sortOrder: 78,
  },
  {
    code: "BND-LAUNCH",
    name: "Business Launch",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 1250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Business Launch",
    active: true,
    sortOrder: 79,
  },
  {
    code: "BND-BEAUTY",
    name: "Beauty & Booking",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 1050000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Beauty & Booking",
    active: true,
    sortOrder: 80,
  },
  {
    code: "BND-REST",
    name: "Restaurant Bundle",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 1850000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Restaurant Bundle",
    active: true,
    sortOrder: 81,
  },
  {
    code: "BND-STORE",
    name: "Online Store",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 2850000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Online Store",
    active: true,
    sortOrder: 82,
  },
  {
    code: "BND-TOUR",
    name: "Tourism Bundle",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 2850000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Tourism Bundle",
    active: true,
    sortOrder: 83,
  },
  {
    code: "BND-RE",
    name: "Real Estate Bundle",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 2650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Real Estate Bundle",
    active: true,
    sortOrder: 84,
  },
  {
    code: "BND-PRES",
    name: "Professional Presence",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 3750000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Professional Presence",
    active: true,
    sortOrder: 85,
  },
  {
    code: "BND-GROW",
    name: "Digital Growth",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 2250000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Digital Growth",
    active: true,
    sortOrder: 86,
  },
  {
    code: "BND-LANG3",
    name: "Three-Language Pack",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription:
      "Bilingual base plus one additional language - less than buying separately",
    active: true,
    sortOrder: 200,
  },
  {
    code: "BND-LANG4",
    name: "Four-Language Pack",
    kind: "BUNDLE",
    category: "Bundles",
    priceTsh: 850000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription:
      "Bilingual base plus two additional languages - less than buying separately",
    active: true,
    sortOrder: 201,
  },
  {
    code: "SEO-FND",
    name: "SEO Foundation",
    kind: "SERVICE",
    category: "SEO",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "SEO Foundation",
    active: true,
    sortOrder: 87,
  },
  {
    code: "SEO-PRO",
    name: "Professional SEO Setup",
    kind: "SERVICE",
    category: "SEO",
    priceTsh: 750000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Professional SEO Setup",
    active: true,
    sortOrder: 88,
  },
  {
    code: "SEO-ADV",
    name: "Advanced SEO Setup",
    kind: "SERVICE",
    category: "SEO",
    priceTsh: 1250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Advanced SEO Setup",
    active: true,
    sortOrder: 89,
  },
  {
    code: "SEO-CARE",
    name: "SEO Care",
    kind: "SUBSCRIPTION_TIER",
    category: "SEO",
    priceTsh: 350000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "SEO Care",
    active: true,
    sortOrder: 90,
  },
  {
    code: "SEO-GROW",
    name: "SEO Growth",
    kind: "SUBSCRIPTION_TIER",
    category: "SEO",
    priceTsh: 650000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "SEO Growth",
    active: true,
    sortOrder: 91,
  },
  {
    code: "SEO-AUTH",
    name: "SEO Authority",
    kind: "SUBSCRIPTION_TIER",
    category: "SEO",
    priceTsh: 1100000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "SEO Authority",
    active: true,
    sortOrder: 92,
  },
  {
    code: "LOC-GBP",
    name: "Google Business Profile",
    kind: "SERVICE",
    category: "Local Search",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Google Business Profile",
    active: true,
    sortOrder: 93,
  },
  {
    code: "LOC-OPT",
    name: "Local Search Optimization",
    kind: "SERVICE",
    category: "Local Search",
    priceTsh: 250000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Local Search Optimization",
    active: true,
    sortOrder: 94,
  },
  {
    code: "LOC-REV",
    name: "Review Strategy Setup",
    kind: "SERVICE",
    category: "Local Search",
    priceTsh: 100000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Review Strategy Setup",
    active: true,
    sortOrder: 95,
  },
  {
    code: "SOC-ESS",
    name: "Social Essential",
    kind: "SUBSCRIPTION_TIER",
    category: "Social Media",
    priceTsh: 350000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Essential",
    active: true,
    sortOrder: 96,
  },
  {
    code: "SOC-GROW",
    name: "Social Growth",
    kind: "SUBSCRIPTION_TIER",
    category: "Social Media",
    priceTsh: 650000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Growth",
    active: true,
    sortOrder: 97,
  },
  {
    code: "SOC-PRO",
    name: "Social Pro",
    kind: "SUBSCRIPTION_TIER",
    category: "Social Media",
    priceTsh: 1000000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Pro",
    active: true,
    sortOrder: 98,
  },
  {
    code: "SOC-CORP",
    name: "Social Corporate",
    kind: "SUBSCRIPTION_TIER",
    category: "Social Media",
    priceTsh: 1750000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Corporate",
    active: true,
    sortOrder: 99,
  },
  {
    code: "ADS-META-S",
    name: "Meta Ads Setup",
    kind: "SERVICE",
    category: "Advertising",
    priceTsh: 200000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Meta Ads Setup",
    active: true,
    sortOrder: 100,
  },
  {
    code: "ADS-META-M",
    name: "Meta Management",
    kind: "SERVICE",
    category: "Advertising",
    priceTsh: 300000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Meta Management",
    active: true,
    sortOrder: 101,
  },
  {
    code: "ADS-GOOG-S",
    name: "Google Ads Setup",
    kind: "SERVICE",
    category: "Advertising",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Google Ads Setup",
    active: true,
    sortOrder: 102,
  },
  {
    code: "ADS-GOOG-M",
    name: "Google Management",
    kind: "SERVICE",
    category: "Advertising",
    priceTsh: 400000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Google Management",
    active: true,
    sortOrder: 103,
  },
  {
    code: "BR-LOGOR",
    name: "Logo Refresh",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 300000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Logo Refresh",
    active: true,
    sortOrder: 104,
  },
  {
    code: "BR-LOGO",
    name: "Professional Logo",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 500000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Professional Logo",
    active: true,
    sortOrder: 105,
  },
  {
    code: "BR-VIS",
    name: "Visual Identity",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 900000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Visual Identity",
    active: true,
    sortOrder: 106,
  },
  {
    code: "BR-GUIDE",
    name: "Brand Guidelines",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Brand Guidelines",
    active: true,
    sortOrder: 107,
  },
  {
    code: "BR-CARD",
    name: "Business Card",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Business Card",
    active: true,
    sortOrder: 108,
  },
  {
    code: "BR-LETTER",
    name: "Letterhead",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 100000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Letterhead",
    active: true,
    sortOrder: 109,
  },
  {
    code: "BR-PROF",
    name: "Company Profile",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Company Profile",
    active: true,
    sortOrder: 110,
  },
  {
    code: "BR-DECK",
    name: "Corporate Deck",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 450000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Corporate Deck",
    active: true,
    sortOrder: 111,
  },
  {
    code: "BR-BROCH",
    name: "Brochure / Catalogue",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Brochure / Catalogue",
    active: true,
    sortOrder: 112,
  },
  {
    code: "BR-SOCIAL",
    name: "Social Visual System",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 350000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Social Visual System",
    active: true,
    sortOrder: 113,
  },
  {
    code: "COPY-1",
    name: "One-page Copywriting",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 200000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "One-page Copywriting",
    active: true,
    sortOrder: 114,
  },
  {
    code: "COPY-5",
    name: "Up to 5 Pages Copywriting",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 400000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Up to 5 Pages Copywriting",
    active: true,
    sortOrder: 115,
  },
  {
    code: "COPY-10",
    name: "Up to 10 Pages Copywriting",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 650000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Up to 10 Pages Copywriting",
    active: true,
    sortOrder: 116,
  },
  {
    code: "COPY-20",
    name: "Up to 20 Pages Copywriting",
    kind: "SERVICE",
    category: "Branding & Content",
    priceTsh: 1100000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Up to 20 Pages Copywriting",
    active: true,
    sortOrder: 117,
  },
  {
    code: "MEDIA-PROD",
    name: "Photography & Video",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Branding & Content",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Photography & Video",
    active: true,
    sortOrder: 118,
  },
  {
    code: "KB-LAUNCH",
    name: "KasiTech Business Launch",
    kind: "SUBSCRIPTION_TIER",
    category: "KasiTech Business",
    priceTsh: 150000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "KasiTech Business Launch",
    active: true,
    sortOrder: 119,
  },
  {
    code: "KB-GROW",
    name: "KasiTech Business Growth",
    kind: "SUBSCRIPTION_TIER",
    category: "KasiTech Business",
    priceTsh: 400000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "KasiTech Business Growth",
    active: true,
    sortOrder: 120,
  },
  {
    code: "KB-PRO",
    name: "KasiTech Business Pro",
    kind: "SUBSCRIPTION_TIER",
    category: "KasiTech Business",
    priceTsh: 800000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "KasiTech Business Pro",
    active: true,
    sortOrder: 121,
  },
  {
    code: "KB-SCALE",
    name: "KasiTech Business Scale",
    kind: "SUBSCRIPTION_TIER",
    category: "KasiTech Business",
    priceTsh: 1500000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "KasiTech Business Scale",
    active: true,
    sortOrder: 122,
  },
  {
    code: "KB-ENT",
    name: "KasiTech Business Enterprise",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "KasiTech Business",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "KasiTech Business Enterprise",
    active: true,
    sortOrder: 123,
  },
  {
    code: "CUS-WEBAPP",
    name: "Custom Web Application",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Custom Web Application",
    active: true,
    sortOrder: 124,
  },
  {
    code: "CUS-CRM",
    name: "CRM / Inventory / Operations System",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "CRM / Inventory / Operations System",
    active: true,
    sortOrder: 125,
  },
  {
    code: "CUS-DASH",
    name: "Dashboard / Data Platform",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Dashboard / Data Platform",
    active: true,
    sortOrder: 126,
  },
  {
    code: "CUS-AI",
    name: "AI / Automation System",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "AI / Automation System",
    active: true,
    sortOrder: 127,
  },
  {
    code: "CUS-MOBILE",
    name: "Mobile Application",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Mobile Application",
    active: true,
    sortOrder: 128,
  },
  {
    code: "CUS-API",
    name: "API / Third-party Integration",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Custom Solutions",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "API / Third-party Integration",
    active: true,
    sortOrder: 129,
  },
  {
    code: "CARE-ESS",
    name: "Essential Care",
    kind: "SUBSCRIPTION_TIER",
    category: "Care & Maintenance",
    priceTsh: 180000,
    billing: "ANNUAL",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Essential Care",
    active: true,
    sortOrder: 130,
  },
  {
    code: "CARE-STD",
    name: "Standard Care",
    kind: "SUBSCRIPTION_TIER",
    category: "Care & Maintenance",
    priceTsh: 300000,
    billing: "ANNUAL",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Standard Care",
    active: true,
    sortOrder: 131,
  },
  {
    code: "CARE-BUS",
    name: "Business Care",
    kind: "SUBSCRIPTION_TIER",
    category: "Care & Maintenance",
    priceTsh: 600000,
    billing: "ANNUAL",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Business Care",
    active: true,
    sortOrder: 132,
  },
  {
    code: "CARE-PRO",
    name: "Professional Care",
    kind: "SUBSCRIPTION_TIER",
    category: "Care & Maintenance",
    priceTsh: 150000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Professional Care",
    active: true,
    sortOrder: 133,
  },
  {
    code: "CARE-PRI",
    name: "Priority Care",
    kind: "SUBSCRIPTION_TIER",
    category: "Care & Maintenance",
    priceTsh: 300000,
    billing: "MONTHLY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Priority Care",
    active: true,
    sortOrder: 134,
  },
  {
    code: "HOST-EMAIL",
    name: "Business email setup",
    kind: "SERVICE",
    category: "Hosting",
    priceTsh: 150000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Business email setup",
    active: true,
    sortOrder: 135,
  },
  {
    code: "HOST-EMAIL-ADD",
    name: "Additional email setup",
    kind: "SERVICE",
    category: "Hosting",
    priceTsh: 25000,
    billing: "ONE_TIME",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Additional email setup",
    active: true,
    sortOrder: 136,
  },
  {
    code: "HOST-DOMAIN",
    name: "Domain registration / renewal",
    kind: "THIRD_PARTY_COST",
    category: "Hosting",
    priceTsh: null,
    billing: "THIRD_PARTY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Domain registration / renewal",
    active: true,
    sortOrder: 137,
  },
  {
    code: "HOST-HOSTING",
    name: "Website hosting",
    kind: "THIRD_PARTY_COST",
    category: "Hosting",
    priceTsh: null,
    billing: "THIRD_PARTY",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Website hosting",
    active: true,
    sortOrder: 138,
  },
  {
    code: "HOST-SSL",
    name: "SSL certificate",
    kind: "ENTITLEMENT",
    category: "Hosting",
    priceTsh: null,
    billing: "INCLUDED",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Included with supported hosting",
    active: true,
    sortOrder: 139,
  },
  {
    code: "DEL-STD",
    name: "Standard Delivery",
    kind: "DELIVERY_OPTION",
    category: "Delivery",
    priceTsh: 0,
    billing: "INCLUDED",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Standard Delivery",
    active: true,
    sortOrder: 140,
  },
  {
    code: "DEL-PRI",
    name: "Priority Delivery",
    kind: "DELIVERY_OPTION",
    category: "Delivery",
    priceTsh: null,
    billing: "SURCHARGE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "+25%",
    active: true,
    sortOrder: 141,
  },
  {
    code: "DEL-RUSH",
    name: "Rush Delivery",
    kind: "DELIVERY_OPTION",
    category: "Delivery",
    priceTsh: null,
    billing: "SURCHARGE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "+40%",
    active: true,
    sortOrder: 142,
  },
  {
    code: "DEL-EMER",
    name: "Accelerated / Emergency Delivery",
    kind: "DELIVERY_OPTION",
    category: "Delivery",
    priceTsh: null,
    billing: "SURCHARGE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "+50%",
    active: true,
    sortOrder: 143,
  },
  {
    code: "DISC-COMPLEX",
    name: "Formal Discovery Phase",
    kind: "CUSTOM_QUOTE_ITEM",
    category: "Discovery",
    priceTsh: null,
    billing: "CUSTOM_QUOTE",
    timelineMinDays: null,
    timelineMaxDays: null,
    timelineImpactDays: null,
    clientDescription: "Formal Discovery Phase",
    active: true,
    sortOrder: 144,
  },
];

export const CANONICAL_ITEM_COUNT = 146 as const;
