#!/usr/bin/env node
/**
 * Production build for the standalone Jembe Group site.
 * Injects form-service environment variables, writes the Vercel static
 * output to dist/, and fails if Kasitech preview paths or assets are missing.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dist = path.join(root, "dist");

function writeConfig() {
  const endpoint = (process.env.JEMBE_FORM_ENDPOINT || "").trim();
  const accessKey = (process.env.JEMBE_FORM_ACCESS_KEY || "").trim();
  const email = (process.env.JEMBE_MANDATE_EMAIL || "info@jembegroup.com").trim();
  const siteOrigin = (process.env.JEMBE_SITE_ORIGIN || "https://jembegroupllc.com").replace(/\/$/, "");

  const js = `/**
 * Generated by scripts/build.mjs — do not put private secrets here.
 */
window.JEMBE_CONFIG = {
  siteOrigin: ${JSON.stringify(siteOrigin)},
  formEndpoint: ${JSON.stringify(endpoint)},
  formAccessKey: ${JSON.stringify(accessKey)},
  mandateEmail: ${JSON.stringify(email)},
  mandateApi: "/api/mandate",
};
`;
  fs.writeFileSync(path.join(root, "config.js"), js);
  console.log(
    endpoint
      ? `config.js: upstream form endpoint configured`
      : "config.js: mandate posts to /api/mandate (independent of Kasitech)",
  );
}

function copyDist() {
  fs.rmSync(dist, { recursive: true, force: true });
  fs.mkdirSync(path.join(dist, "assets"), { recursive: true });

  const files = [
    "index.html",
    "404.html",
    "styles.css",
    "app.js",
    "config.js",
    "robots.txt",
    "sitemap.xml",
  ];
  for (const file of files) {
    fs.copyFileSync(path.join(root, file), path.join(dist, file));
  }
  fs.cpSync(path.join(root, "assets"), path.join(dist, "assets"), { recursive: true });
  console.log(`Wrote static output to ${path.relative(root, dist)}/`);
}

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name.startsWith(".") || entry.name === "dist" || entry.name === "scripts") continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function validate() {
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
  const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
  const config = fs.readFileSync(path.join(root, "config.js"), "utf8");

  const errors = [];

  for (const [label, text] of [
    ["index.html", html],
    ["styles.css", css],
    ["app.js", app],
    ["config.js", config],
  ]) {
    if (/kasitechinnovations\.com/i.test(text)) {
      errors.push(`${label} still references kasitechinnovations.com`);
    }
    if (/\/preview\/jembe/.test(text)) {
      errors.push(`${label} still references /preview/jembe`);
    }
  }

  if (/noindex/i.test(html)) errors.push("index.html still has noindex");
  if (/KasiTech/.test(html)) errors.push("index.html still names KasiTech");
  if (/class="proposed"/.test(html)) errors.push("index.html still has the preview strip");
  if (/Jembe Group Llc/.test(html)) errors.push("brand lockup still writes Llc instead of LLC");
  if (/as stated in .*Corporate Profile/.test(html)) {
    errors.push("site still cites Corporate Profile 2026 as a source viewers cannot open");
  }
  if (!html.includes('id="page-privacy"') || !html.includes('id="page-terms"') || !html.includes('id="page-cookies"') || !html.includes('id="page-disclaimer"')) {
    errors.push("legal pages are missing");
  }
  if (!html.includes('rel="canonical" href="https://jembegroupllc.com/"')) {
    errors.push("canonical URL is not https://jembegroupllc.com/");
  }

  const refs = new Set();
  const re = /(?:src|href)="(\/[^"]+)"/g;
  let match;
  while ((match = re.exec(html))) refs.add(match[1]);
  const onerror = html.match(/this\.src='(\/[^']+)'/g) || [];
  for (const item of onerror) {
    const m = item.match(/this\.src='(\/[^']+)'/);
    if (m) refs.add(m[1]);
  }

  for (const ref of refs) {
    if (ref.startsWith("http") || ref.startsWith("mailto:") || ref.startsWith("tel:")) continue;
    const filePath = path.join(root, ref.replace(/^\//, ""));
    if (!fs.existsSync(filePath)) {
      errors.push(`missing file for ${ref} (${filePath})`);
    }
  }

  const requiredAssets = [
    "assets/mark.png",
    "assets/mark.svg",
    "assets/shield.svg",
    "assets/energy-hero.jpg",
    "assets/highway.jpg",
    "assets/insurance.jpg",
    "assets/field.jpg",
    "assets/mining.jpg",
    "assets/tower.jpg",
    "assets/city-infra.jpg",
    "assets/tractor.jpg",
    "assets/wind-solar.jpg",
    "assets/water.jpg",
    "assets/construction.jpg",
    "assets/piping.jpg",
    "assets/industrial.jpg",
    "assets/hospital.jpg",
    "assets/pylons.jpg",
    "styles.css",
    "app.js",
    "config.js",
    "robots.txt",
    "sitemap.xml",
    "api/mandate.js",
    "dist/index.html",
    "dist/assets/mark.png",
  ];
  for (const rel of requiredAssets) {
    if (!fs.existsSync(path.join(root, rel))) errors.push(`required file missing: ${rel}`);
  }

  for (const file of walk(root)) {
    if (!/\.(html|js|css|txt|xml|toml|json|md|svg)$/i.test(file)) continue;
    if (file.endsWith("DEPLOYMENT.md") || file.endsWith("README.md")) continue;
    const text = fs.readFileSync(file, "utf8");
    if (file.includes(`${path.sep}scripts${path.sep}`)) continue;
    const hit = text.match(/kasitechinnovations\.com/i);
    if (hit) {
      errors.push(`Kasitech URL in ${path.relative(root, file)}`);
    }
    if (
      /\/preview\/jembe/.test(text) &&
      !file.endsWith("vercel.json") &&
      !file.endsWith("netlify.toml") &&
      !file.endsWith("_redirects")
    ) {
      errors.push(`/preview/jembe in ${path.relative(root, file)}`);
    }
  }

  if (errors.length) {
    console.error("Production checks failed:");
    for (const err of errors) console.error(`  - ${err}`);
    process.exit(1);
  }

  console.log("Production checks passed.");
  console.log("Standalone origin: https://jembegroupllc.com");
}

writeConfig();
copyDist();
validate();
