import type { DemoIndustryId, FeatureGroup } from "../types";

export type DemoActivation =
  | "nav"
  | "section"
  | "cta"
  | "modal"
  | "language"
  | "commerce"
  | "replace_section"
  | "enhancement"
  | "none";

export type FeatureRegistryEntry = {
  featureCode: string;
  demoSupported: boolean;
  industries: DemoIndustryId[] | "all";
  group: FeatureGroup;
  activationBehavior: DemoActivation;
  /** Preview capability flag consumed by DemoWebsiteRenderer */
  previewFlag: string;
  dependencies: string[];
  previewLocation: string;
  shortExplanation: string;
};

/**
 * Feature Registry — demo behavior only. No prices.
 * Maps catalog capabilities → visual / interactive preview behavior.
 */
export const FEATURE_REGISTRY: FeatureRegistryEntry[] = [
  {
    featureCode: "ADD-BLOG",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "nav",
    previewFlag: "blog",
    dependencies: [],
    previewLocation: "nav + /blog",
    shortExplanation: "Publish articles, updates, and SEO content.",
  },
  {
    featureCode: "ADD-TEAM",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "team",
    dependencies: [],
    previewLocation: "nav + team section",
    shortExplanation: "Introduce the people behind your business.",
  },
  {
    featureCode: "ADD-PORT",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "portfolio",
    dependencies: [],
    previewLocation: "portfolio section",
    shortExplanation: "Show selected work or project examples.",
  },
  {
    featureCode: "ADD-CASE",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "cases",
    dependencies: [],
    previewLocation: "case studies",
    shortExplanation: "Tell deeper stories about results you've delivered.",
  },
  {
    featureCode: "ADD-EVT",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "events",
    dependencies: [],
    previewLocation: "events",
    shortExplanation: "List upcoming events with dates and details.",
  },
  {
    featureCode: "ADD-RES",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "resources",
    dependencies: [],
    previewLocation: "resources",
    shortExplanation: "Offer downloadable guides or documents.",
  },
  {
    featureCode: "ADD-CARE",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "careers",
    dependencies: [],
    previewLocation: "careers",
    shortExplanation: "Publish open roles and attract applicants.",
  },
  {
    featureCode: "ADD-MULTI",
    demoSupported: true,
    industries: "all",
    group: "advanced",
    activationBehavior: "enhancement",
    previewFlag: "multiLocation",
    dependencies: [],
    previewLocation: "locations directory",
    shortExplanation: "List multiple business locations with directions.",
  },
  {
    featureCode: "LANG-ENSW",
    demoSupported: true,
    industries: "all",
    group: "advanced",
    activationBehavior: "language",
    previewFlag: "multilingual",
    dependencies: [],
    previewLocation: "language selector",
    shortExplanation: "Let visitors switch between any two languages.",
  },
  {
    featureCode: "LOC-GBP",
    demoSupported: true,
    industries: "all",
    group: "local",
    activationBehavior: "none",
    previewFlag: "googleBusiness",
    dependencies: [],
    previewLocation: "build summary / local presence",
    shortExplanation: "Get found on Google Maps and Search with a polished Business Profile.",
  },
  {
    featureCode: "LOC-OPT",
    demoSupported: true,
    industries: "all",
    group: "local",
    activationBehavior: "none",
    previewFlag: "localOptimization",
    dependencies: [],
    previewLocation: "build summary / local presence",
    shortExplanation: "Strengthen local search signals for your area.",
  },
  {
    featureCode: "LOC-REV",
    demoSupported: true,
    industries: "all",
    group: "local",
    activationBehavior: "enhancement",
    previewFlag: "reviews",
    dependencies: [],
    previewLocation: "testimonials / reviews",
    shortExplanation: "Plan how customers leave and see reviews that build trust.",
  },
  {
    featureCode: "ADD-MAP",
    demoSupported: true,
    industries: "all",
    group: "website",
    activationBehavior: "section",
    previewFlag: "map",
    dependencies: [],
    previewLocation: "contact / map",
    shortExplanation: "Show where you are on a map.",
  },
  {
    featureCode: "ADD-INQ",
    demoSupported: true,
    industries: "all",
    group: "website",
    activationBehavior: "cta",
    previewFlag: "inquiry",
    dependencies: [],
    previewLocation: "inquiry form",
    shortExplanation: "Collect structured enquiries from visitors.",
  },
  {
    featureCode: "ADD-SRCH",
    demoSupported: true,
    industries: "all",
    group: "advanced",
    activationBehavior: "enhancement",
    previewFlag: "search",
    dependencies: [],
    previewLocation: "site search",
    shortExplanation: "Help visitors find pages and products quickly.",
  },
  {
    featureCode: "BKG-APT",
    demoSupported: true,
    industries: ["beauty", "healthcare", "professional", "general"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "bookingApt",
    dependencies: [],
    previewLocation: "Book appointment CTA + modal",
    shortExplanation: "Let customers choose a service, date, and time online.",
  },
  {
    featureCode: "BKG-STAFF",
    demoSupported: true,
    industries: ["beauty", "healthcare", "professional"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "bookingStaff",
    dependencies: [],
    previewLocation: "Multi-staff booking",
    shortExplanation: "Customers can pick a preferred staff member.",
  },
  {
    featureCode: "BKG-EXT",
    demoSupported: true,
    industries: ["beauty", "healthcare", "general"],
    group: "booking",
    activationBehavior: "cta",
    previewFlag: "bookingExternal",
    dependencies: [],
    previewLocation: "external booking link",
    shortExplanation: "Link out to your existing booking tool.",
  },
  {
    featureCode: "BKG-REST",
    demoSupported: true,
    industries: ["restaurant", "hotel"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "reservations",
    dependencies: [],
    previewLocation: "Reserve a table",
    shortExplanation: "Take table reservations with party size and time.",
  },
  {
    featureCode: "BKG-TOUR",
    demoSupported: true,
    industries: ["tourism"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "tourBooking",
    dependencies: ["TOUR-CAT"],
    previewLocation: "tour booking",
    shortExplanation: "Book a tour from the catalog.",
  },
  {
    featureCode: "BKG-HOTINT",
    demoSupported: true,
    industries: ["hotel"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "hotelBooking",
    dependencies: [],
    previewLocation: "room booking",
    shortExplanation: "Integrated hotel room enquiry / booking flow.",
  },
  {
    featureCode: "PAY-STD",
    demoSupported: true,
    industries: "all",
    group: "payments",
    activationBehavior: "cta",
    previewFlag: "payments",
    dependencies: [],
    previewLocation: "pay / checkout actions",
    shortExplanation: "Accept online payments such as M-Pesa or cards.",
  },
  {
    featureCode: "PAY-DON",
    demoSupported: true,
    industries: ["ngo"],
    group: "payments",
    activationBehavior: "cta",
    previewFlag: "donate",
    dependencies: [],
    previewLocation: "donate CTA",
    shortExplanation: "Accept one-off donations online.",
  },
  {
    featureCode: "ECOM-START",
    demoSupported: true,
    industries: ["retail", "general", "beauty"],
    group: "commerce",
    activationBehavior: "commerce",
    previewFlag: "store",
    dependencies: [],
    previewLocation: "Shop + cart",
    shortExplanation: "Sell products with a simple online store.",
  },
  {
    featureCode: "ECOM-BUS",
    demoSupported: true,
    industries: ["retail"],
    group: "commerce",
    activationBehavior: "commerce",
    previewFlag: "storeBusiness",
    dependencies: [],
    previewLocation: "enhanced store",
    shortExplanation: "Larger catalog and richer store operations.",
  },
  {
    featureCode: "ECOM-ADV",
    demoSupported: true,
    industries: ["retail"],
    group: "commerce",
    activationBehavior: "commerce",
    previewFlag: "storeAdvanced",
    dependencies: [],
    previewLocation: "advanced store",
    shortExplanation: "Advanced storefront capabilities for growth.",
  },
  {
    featureCode: "REST-MENU",
    demoSupported: true,
    industries: ["restaurant", "hotel"],
    group: "commerce",
    activationBehavior: "section",
    previewFlag: "menu",
    dependencies: [],
    previewLocation: "digital menu",
    shortExplanation: "Publish your menu online.",
  },
  {
    featureCode: "REST-AMENU",
    demoSupported: true,
    industries: ["restaurant", "hotel"],
    group: "commerce",
    activationBehavior: "replace_section",
    previewFlag: "menuAdvanced",
    dependencies: [],
    previewLocation: "filterable menu",
    shortExplanation: "Categorized, filterable menu experience.",
  },
  {
    featureCode: "REST-ORDER",
    demoSupported: true,
    industries: ["restaurant"],
    group: "commerce",
    activationBehavior: "cta",
    previewFlag: "ordering",
    dependencies: ["REST-MENU"],
    previewLocation: "order CTA",
    shortExplanation: "Let guests place orders from the menu.",
  },
  {
    featureCode: "REST-QR",
    demoSupported: true,
    industries: ["restaurant"],
    group: "advanced",
    activationBehavior: "enhancement",
    previewFlag: "menuQr",
    dependencies: ["REST-MENU"],
    previewLocation: "QR menu badge",
    shortExplanation: "QR access to your digital menu.",
  },
  {
    featureCode: "TOUR-CAT",
    demoSupported: true,
    industries: ["tourism"],
    group: "commerce",
    activationBehavior: "section",
    previewFlag: "tours",
    dependencies: [],
    previewLocation: "tour cards",
    shortExplanation: "Browse tours with prices and durations.",
  },
  {
    featureCode: "TOUR-ITIN",
    demoSupported: true,
    industries: ["tourism"],
    group: "commerce",
    activationBehavior: "enhancement",
    previewFlag: "itinerary",
    dependencies: ["TOUR-CAT"],
    previewLocation: "itinerary detail",
    shortExplanation: "Day-by-day itinerary for each tour.",
  },
  {
    featureCode: "TOUR-INQ",
    demoSupported: true,
    industries: ["tourism"],
    group: "booking",
    activationBehavior: "cta",
    previewFlag: "tourInquiry",
    dependencies: ["TOUR-CAT"],
    previewLocation: "tour enquiry",
    shortExplanation: "Enquire about a tour without full booking.",
  },
  {
    featureCode: "RE-LIST",
    demoSupported: true,
    industries: ["real-estate"],
    group: "commerce",
    activationBehavior: "section",
    previewFlag: "listings",
    dependencies: [],
    previewLocation: "property listings",
    shortExplanation: "Browse properties for sale or rent.",
  },
  {
    featureCode: "RE-FILT",
    demoSupported: true,
    industries: ["real-estate"],
    group: "commerce",
    activationBehavior: "enhancement",
    previewFlag: "listingFilters",
    dependencies: ["RE-LIST"],
    previewLocation: "listing filters",
    shortExplanation: "Filter by price, type, and location.",
  },
  {
    featureCode: "RE-INQ",
    demoSupported: true,
    industries: ["real-estate"],
    group: "booking",
    activationBehavior: "modal",
    previewFlag: "propertyInquiry",
    dependencies: ["RE-LIST"],
    previewLocation: "property enquiry",
    shortExplanation: "Send an enquiry about a specific property.",
  },
  {
    featureCode: "RE-MAP",
    demoSupported: true,
    industries: ["real-estate"],
    group: "advanced",
    activationBehavior: "enhancement",
    previewFlag: "propertyMap",
    dependencies: ["RE-LIST"],
    previewLocation: "map view",
    shortExplanation: "See properties on a map.",
  },
  {
    featureCode: "RE-AGENT",
    demoSupported: true,
    industries: ["real-estate"],
    group: "content",
    activationBehavior: "section",
    previewFlag: "agents",
    dependencies: [],
    previewLocation: "agents",
    shortExplanation: "Introduce your agents or team.",
  },
  {
    featureCode: "LOG-TRACK",
    demoSupported: true,
    industries: ["logistics"],
    group: "commerce",
    activationBehavior: "section",
    previewFlag: "tracking",
    dependencies: [],
    previewLocation: "shipment tracking",
    shortExplanation: "Customers track shipments with a reference number.",
  },
  {
    featureCode: "LOG-API",
    demoSupported: true,
    industries: ["logistics"],
    group: "advanced",
    activationBehavior: "replace_section",
    previewFlag: "trackingLive",
    dependencies: [],
    previewLocation: "live tracking",
    shortExplanation: "Richer live tracking experience.",
  },
  {
    featureCode: "LOG-QUOTE",
    demoSupported: true,
    industries: ["logistics"],
    group: "booking",
    activationBehavior: "cta",
    previewFlag: "logisticsQuote",
    dependencies: [],
    previewLocation: "quote request",
    shortExplanation: "Request a shipping quote online.",
  },
  {
    featureCode: "EDU-ADM",
    demoSupported: true,
    industries: ["education"],
    group: "booking",
    activationBehavior: "cta",
    previewFlag: "admissions",
    dependencies: [],
    previewLocation: "admissions",
    shortExplanation: "Start an admissions enquiry.",
  },
  {
    featureCode: "EDU-COURSE",
    demoSupported: true,
    industries: ["education"],
    group: "content",
    activationBehavior: "section",
    previewFlag: "courses",
    dependencies: [],
    previewLocation: "courses",
    shortExplanation: "List programs and courses.",
  },
  {
    featureCode: "EDU-FAC",
    demoSupported: true,
    industries: ["education"],
    group: "content",
    activationBehavior: "section",
    previewFlag: "faculty",
    dependencies: [],
    previewLocation: "faculty",
    shortExplanation: "Introduce faculty or instructors.",
  },
  {
    featureCode: "NGO-PROG",
    demoSupported: true,
    industries: ["ngo"],
    group: "content",
    activationBehavior: "section",
    previewFlag: "programs",
    dependencies: [],
    previewLocation: "programs",
    shortExplanation: "Showcase programs and impact areas.",
  },
  {
    featureCode: "NGO-VOL",
    demoSupported: true,
    industries: ["ngo"],
    group: "booking",
    activationBehavior: "cta",
    previewFlag: "volunteer",
    dependencies: [],
    previewLocation: "volunteer",
    shortExplanation: "Collect volunteer interest.",
  },
  {
    featureCode: "HLTH-DIR",
    demoSupported: true,
    industries: ["healthcare"],
    group: "content",
    activationBehavior: "section",
    previewFlag: "practitioners",
    dependencies: [],
    previewLocation: "practitioners",
    shortExplanation: "Directory of practitioners and services.",
  },
  {
    featureCode: "ENT-GALLERY",
    demoSupported: true,
    industries: "all",
    group: "content",
    activationBehavior: "section",
    previewFlag: "gallery",
    dependencies: [],
    previewLocation: "gallery",
    shortExplanation: "Photo gallery of your work or space.",
  },
  {
    featureCode: "ENT-SOCIAL-INTEGRATION",
    demoSupported: true,
    industries: "all",
    group: "marketing",
    activationBehavior: "enhancement",
    previewFlag: "socialLinks",
    dependencies: [],
    previewLocation: "social links",
    shortExplanation: "Connect visitors to your social profiles.",
  },
];

export function registryByCode(): Map<string, FeatureRegistryEntry> {
  return new Map(FEATURE_REGISTRY.map((e) => [e.featureCode, e]));
}

export function isFeatureRelevant(
  entry: FeatureRegistryEntry,
  industry: DemoIndustryId | null,
): boolean {
  if (!industry) return true;
  if (entry.industries === "all") return true;
  return entry.industries.includes(industry);
}
