import { loadPriceBook } from "@/commercial";

/** Concise customer-facing outcome for build summary lines. */
export function outcomeForCode(code: string): string {
  const map: Record<string, string> = {
    "WEB-ONE": "A focused one-page presence for your business",
    "WEB-ESS": "A clear multi-page website for everyday customers",
    "WEB-BUS": "A fuller business website with room to grow",
    "WEB-BUSP": "A stronger business site with richer structure",
    "WEB-PRO": "A professional site built for credibility and enquiry",
    "WEB-SIG": "A signature website for a premium brand presence",
    "BKG-APT": "Customers can book appointments online",
    "BKG-STAFF": "Customers choose a staff member when booking",
    "BKG-EXT": "Connect booking to your existing tool",
    "BKG-REST": "Guests can reserve a table online",
    "BKG-TOUR": "Travellers can book tours from your site",
    "BKG-HOTINT": "Guests can request hotel stays online",
    "REST-MENU": "Guests can browse your menu on any phone",
    "REST-AMENU": "Guests can filter menu categories and dietary info",
    "REST-ORDER": "Guests can place demo orders from the menu",
    "REST-QR": "Table QR links straight to your digital menu",
    "PAY-STD": "Accept deposits or payments where you need them",
    "PAY-DON": "Accept donations through a clear giving flow",
    "ECOM-START": "Sell products from a simple online store",
    "ECOM-BUS": "Run a fuller store with stronger catalogue tools",
    "ECOM-ADV": "Advanced store capabilities for growing sales",
    "TOUR-CAT": "Showcase tours as clear bookable products",
    "TOUR-ITIN": "Show day-by-day itineraries that build trust",
    "TOUR-INQ": "Capture tour enquiries when visitors are ready",
    "RE-LIST": "List properties with price and key details",
    "RE-FILT": "Help buyers filter by area, beds, and budget",
    "RE-INQ": "Collect property enquiries from serious buyers",
    "RE-MAP": "Show where listings sit on a map",
    "RE-AGENT": "Introduce agents who handle each property",
    "LOG-TRACK": "Customers can track shipments online",
    "LOG-API": "Live tracking powered by your logistics feed",
    "LOC-GBP": "Get found on Google Maps and local Search",
    "LOC-OPT": "Strengthen how you show up in local search",
    "LOC-REV": "Guide customers to leave and find reviews",
    "LANG-ENSW": "Visitors can switch between English and Swahili",
    "ADD-MULTI": "List multiple locations with directions",
    "ADD-INQ": "Make it easy for customers to contact you",
    "ADD-TEAM": "Introduce the people behind your business",
    "ADD-EVT": "Promote upcoming events on your site",
    "ENT-GALLERY": "Show your work and atmosphere in a gallery",
    "SEO-FND": "Lay the foundation for search visibility",
    "SEO-PRO": "Stronger SEO setup for competitive search",
    "SEO-ADV": "Advanced SEO setup for ambitious growth",
    "CARE-ESS": "Essential website care and updates",
    "CARE-STD": "Steady care with more hands-on support",
    "CARE-BUS": "Business-level care for active websites",
    "CARE-PRO": "Pro care for higher-stakes digital presence",
    "CARE-PRI": "Priority care with the closest support tier",
    "KB-LAUNCH": "Owner tools for website basics and analytics",
    "KB-GROW": "Owner tools for bookings, customers, and more",
    "BND-BEAUTY": "Beauty starter bundle — site, booking path, local presence",
    "BND-REST": "Restaurant bundle — site, menu, reservations, local presence",
    "BND-TOUR": "Tourism bundle — site, tours, itineraries, enquiries",
    "BND-RE": "Real-estate bundle — site, listings, filters, enquiries",
    "BND-STORE": "Store bundle — site, starter shop, payments",
    "BND-PRES": "Professional presence — site, SEO, local profile",
    "BND-LAUNCH": "Launch bundle for a fast credible start",
  };
  if (map[code]) return map[code];
  const item = loadPriceBook().itemByCode.get(code);
  return (
    item?.clientDescription?.split(".")[0]?.trim() || item?.name || code
  );
}
