/**
 * Generated by scripts/build.mjs — do not put private secrets here.
 */
window.JEMBE_CONFIG = {
  siteOrigin: "https://jembegroupllc.com",
  formEndpoint: "",
  formAccessKey: "",
  mandateEmail: "info@jembegroup.com",
  mandateApi: "/api/mandate",
};
